name: Update installed tools

on:
  repository_dispatch:
    types: update-tools
  schedule:
    - cron:  '14 4 * * 6'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ssh-key: ${{ secrets.GHA_DEPLOY_KEY }}
        fetch-depth: '2'
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Cache .venv3
      id: venv3
      uses: actions/cache@v2
      with:
        path: .venv3
        key: ${{ runner.os }}-venv3
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install virtualenv
        virtualenv -p python3 .venv3
        . ".venv3/bin/activate"
        if [ -f jenkins/requirements.yml ]; then pip install -r jenkins/requirements.yml; fi
        cp jenkins/requirements.yml .venv3/cached_requirements.yml
      #if: '(test ! -f .venv3/cached_requirements.yml && echo Cache does not exist) || echo Cache does exist, skipping step'
      #if: steps.venv3.outputs.cache-hit != 'true'
    - name: Update tools
      shell: bash
      env:
        PRODUCTION_API_KEY: ${{ secrets.PRODUCTION_API_KEY }}
        STAGING_API_KEY: ${{ secrets.STAGING_API_KEY }}
      run: |
        git config --local user.email "github-actions@usegalaxy.no"
        git config --local user.name "usegalaxy.no actions"
        bash jenkins/main.sh update
